workflows:
  unity-ios-unsigned:
    name: Unity iOS Unsigned IPA
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
    scripts:
      - name: Build unsigned ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --no-sign
    artifacts:
      - build/ios/ipa/*.ipa
