workflows:
  ios-xcode:
    name: iOS Xcode Build
    environment:
      xcode: 16.4   # hoặc latest
    scripts:
      - name: Build .ipa from Xcode project
        script: |
          xcode-project build-ipa \
            --workspace "Unity-iPhone.xcworkspace" \
            --scheme "Unity-iPhone"
    artifacts:
      - build/ios/ipa/*.ipa
