workflows:
  unity-ios:
    name: Unity iOS Build
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
    scripts:
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
